# Generated by Django 4.0.4 on 2022-04-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_active_product_deal_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='discountPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
