# Generated by Django 4.0.4 on 2022-04-23 07:34

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[utils.validators.validate_category]),
        ),
    ]
