# Generated by Django 4.0.4 on 2022-04-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
