# Generated by Django 4.0.4 on 2022-05-03 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[utils.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.SmallIntegerField(blank=True, null=True, validators=[utils.validators.validate_quantity]),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[utils.validators.validate_user]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.SmallIntegerField(default=1, validators=[utils.validators.validate_quantity]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[utils.validators.validate_user]),
        ),
    ]
